# syntax=docker/dockerfile:1

FROM node:24.0.1-slim AS development

COPY . /app
WORKDIR /app

FROM development AS prod-deps
RUN npm ci --omit=dev
FROM development AS build
RUN npm ci
RUN npm run build

FROM development
COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/build /app/build
EXPOSE 3000
CMD [ "npm", "run", "start" ]